[package]
name = "pixelflut"

authors = ["NotNite", "Philpax"]
description = "A synchronous library for connecting to Pixelflut"
edition = "2021"
version = "0.1.0"

[dependencies]
tokio = { version = "1.19.0", features = ["net", "io-util"] }
